pkg/server/definition.go, pkg/server/definition_test.go, pkg/server/testdata/goto-functions.libsonnet
This adds support to go to definition for any parameter used within a function
Closes https://github.com/grafana/jsonnet-language-server/issues/14
=> Go to definition: Function parameters

pkg/position/point.go, pkg/position/range.go, pkg/processing/find.go, pkg/server/definition.go, pkg/server/diagnostics.go, pkg/server/execute.go, pkg/server/hover.go, pkg/server/server.go
This moves things away from the `definition.go` file where everything is happening
The new `processing` package only deals with the jsonnet `ast` package and doesn't import the `protocol`.
All conversions happen on the server level now and don't make it down into processing
**Note that this is a first refactoring step, it is not perfect and can be further improved**
=> Move processing out of the `server` package

pkg/nodestack/nodestack.go, pkg/processing/find_bind.go, pkg/processing/find_field.go, pkg/processing/find_param.go, pkg/processing/find_position.go, pkg/server/definition.go
Here are the main feature of this PR:
* Processing functions are split into multiple files
* Tests are unmodified, they still pass the same way
* Finding a field now returns an array of `objectRange` instead of a field directly. This will allow us to implement issues that require multiple definitions (such as listing overrides and getting autocomplete)
* Finding a parameter has been split from finding a var bind (as suggested here: https://github.com/grafana/jsonnet-language-server/pull/16)
=> Split find into multiple files

nix/default.nix
- Replace deprecated `buildFlagsArray` argument with `ldflags` attribute (see [here](https://github.com/NixOS/nixpkgs/blob/b99fc173da1621ddb933c081e79e22d44d489b23/pkgs/development/go-modules/generic/default.nix#L274-L276))
- Update version to `0.6.3`
- Point `src` to repository root (`../.`)
Tested successfully with on macOS Monterey (12.0.1):
```bash
$ nix build ./nix
$ ./result/bin/jsonnet-language-server --version
jsonnet-language-server version 0.6.3
```
=> Update Nix derivation attributes

RELEASES.md, nix/release, nix/shell.nix
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
=> Document how to update the Nix flake derivation

pkg/position/range.go, pkg/processing/find_field.go, pkg/processing/object.go, pkg/server/definition_test.go, pkg/server/testdata/goto-self-out-of-scope.jsonnet
Fields outside of the scope of `self` are currently being resolved
See the test for an example
Fixes https://github.com/grafana/jsonnet-language-server/issues/2
=> Fix `self` scope

pkg/nodestack/nodestack.go, pkg/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-self-complex-scoping.jsonnet, pkg/server/testdata/goto-self-out-of-scope.jsonnet
Follow-up to https://github.com/grafana/jsonnet-language-server/pull/23
See the test file for examples. Fetching `self.sub2` and `self.test3` now works!
=> `self` complex scope improvements

pkg/server/definition.go, pkg/server/definition_test.go, pkg/server/utils_test.go
The `processing.FindRangesFromIndexList` function already returned a list of object ranges (never more than one in it for now, though)
However, this list didn't make it up to the server's `Definition` method.
This refactors the server code and the tests to allow us to return and test for a list of locations. All that will remain (so easy, right) is to modify the `processing` package code
Progress towards https://github.com/grafana/jsonnet-language-server/issues/6
=> Go-to-definition: Return a list of Locations all the way to the top

pkg/processing/find_field.go, pkg/server/definition_test.go, pkg/server/utils_test.go
Handles all cases from the new `goto-overrides.jsonnet` file. Example:
There are still some cases to consider for https://github.com/grafana/jsonnet-language-server/issues/6 (like considering multiple definitions when an import is considered), so it's not ready to close yet
=> Return multiple definitions: Simple cases

pkg/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-overrides-base.jsonnet, pkg/server/testdata/goto-overrides.jsonnet
Yet another case for https://github.com/grafana/jsonnet-language-server/issues/6
This supports two cases:
- Definitions across multiple files
- The case where a local is used in the second file. We were currently using the initial stack to find the bind for that var. Across files, that doesn't work, we have to work with the stack where the var is being used
=> Support multiple definitions: Locals

pkg/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-overrides-base.jsonnet, pkg/server/testdata/goto-overrides-imported2.jsonnet, pkg/server/testdata/goto-overrides.jsonnet
Whenever a binary operator was in the chain, it would make all fields to not be found further down the line
This supports find fields in constructs like this:
```
{
my_field+: (import 'test') + (import 'test2')
}
```
Note: the tests are getting pretty intense. I'm planning a refactor once I've got the cases I want working. I'll probably set up some benchmarking as well, see if I can find some low-hanging fruits for performance improvements
This builds upon https://github.com/grafana/jsonnet-language-server/pull/30 and https://github.com/grafana/jsonnet-language-server/pull/31
Issue: #6
=> Support multiple definitons: Binary operators

pkg/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-import-nested-main.jsonnet, pkg/server/testdata/goto-import-nested-obj.libsonnet, pkg/server/testdata/goto-import-nested1.libsonnet, pkg/server/testdata/goto-import-nested2.libsonnet, pkg/server/testdata/goto-import-nested3.libsonnet
Some references to vars and self were lost along the way
This works for most use cases now
There's still some refactoring done, both for performance and for cleanliness (lots of repeated code) but it all works now
I will add a video on the README once this is merged
Closes https://github.com/grafana/jsonnet-language-server/issues/6
=> Full multiple definitions support

pkg/server/definition.go, pkg/server/definition_test.go
Instead, just log the error. If we fail the request completely, the client (in my case vscode) goes crazy and may even kill the language server
However, it's a pretty normal scenario that the AST is not valid (when modifying jsonnet, for example)
=> Definition: Do not fail the request when there's an error

main.go, pkg/server/definition_test.go, pkg/server/utils_test.go, pkg/utils/stdio.go
I want to refactor this code a bit but it'll be nice to see if the new code is faster
This extracts the test cases and uses them for both testing and benchmarking
To benchmark the code:
1. Run benchmark with the old code: `go test ./... -bench "BenchmarkDefinition/test_goto_definition_for_var_myvar" -count=10 > old.txt`
2. Modify the code
3. Run benchmark again: `go test ./... -bench "BenchmarkDefinition/test_goto_definition_for_var_myvar" -count=10 > new.txt`
4. Compare files: `benchstat old.txt new.txt`
=> Add benchmark test for "go to definition"

pkg/nodestack/nodestack.go, pkg/processing/find_bind.go, pkg/processing/find_field.go, pkg/processing/find_param.go, pkg/processing/find_position.go, pkg/processing/top_level_objects.go, pkg/server/definition.go, pkg/server/execute.go, pkg/server/hover.go, pkg/server/hover_test.go
Removed unnecessary return values in node stack
Added an import cache bringing some performance improvements
Ran some benchmarks. Pretty good improvement 😄 
```
name                                                             old time/op  new time/op  delta
Definition/goto_deeply_nested_imported_attribute-8                162µs ±13%    12µs ± 6%  -92.57%  (p=0.000 n=20+20)
Definition/goto_deeply_nested_imported_attribute_through_self-8   166µs ±10%    48µs ± 9%  -71.35%  (p=0.000 n=20+20)
```
=> Refactoring + Speed improvements

pkg/server/diagnostics.go
Closes https://github.com/grafana/jsonnet-language-server/issues/44
Don't know why I needed this. I just tested again without it and VSCode is clearing the errors successfully :shrug:
=> Remove "no errors" diagnostics

pkg/server/completion.go, pkg/server/completion_test.go, pkg/stdlib/stdlib-content.jsonnet
Closes https://github.com/grafana/jsonnet-language-server/issues/13
This works pretty well out of the box because the args given by the jsonnet docs are valid jsonnet
Ex:
Autocompleting `std.manifestYamlDoc` will give `std.manifestYamlDoc(value, indent_array_in_object=false, quote_keys=true)`
=> Completion: Add in parameters when the suggestion is a function

editor/vim/README.md, go.mod, go.sum, pkg/server/configuration.go, pkg/server/configuration_test.go, pkg/server/formatting.go, pkg/server/formatting_test.go, pkg/server/server.go
Allow users to customize the formatting parameters using LSP runtime configuration, which is modifiable w/o restarting the jsonnet-language-server.
Sample configuration looks like:
```
settings = {
formatting = {
Indent = 4,
StringStyle = 'double',
},
}
```
See `TestConfiguration_Formatting` for a complete list of allowed keys.
=> feat: dynamic formatting configuration

pkg/server/diagnostics.go, pkg/server/diagnostics_test.go
Fixes https://github.com/grafana/jsonnet-language-server/issues/49
The parsing was all wrong in some cases and was quite unsafe. This should no longer panic and it fixes a few issues with parsing
All tested now, too
=> Fix diagnostics line parsing

main.go, pkg/server/configuration.go, pkg/server/configuration_test.go, pkg/server/definition_test.go, pkg/server/diagnostics.go, pkg/server/formatting.go, pkg/server/formatting_test.go, pkg/server/server.go, pkg/server/utils_test.go
Continues @entombedvirus's work in #37 and #47
With this, we can now configure everything using the configuration endpoint
This will allow IDE extensions to change configurations without restarting the server
Command line configs are still supported, for retro-compatibility and for looser integrations (like vim and emacs use)
=> Add support for configuring everything with `DidChangeConfiguration`

pkg/ast_processing/find_bind.go, pkg/ast_processing/find_field.go, pkg/ast_processing/find_param.go, pkg/ast_processing/find_position.go, pkg/ast_processing/object.go, pkg/ast_processing/object_range.go, pkg/ast_processing/range.go, pkg/ast_processing/top_level_objects.go, pkg/server/definition.go, pkg/server/server.go, pkg/server/symbols.go, pkg/server/symbols_test.go, pkg/server/unused.go
Report symbols to clients of the language server
This allows features like the VSCode outline
In the following screenshots, see the tab in the lower left
=> Symbols support

pkg/ast_processing/find_position.go, pkg/server/definition_test.go, pkg/server/testdata/goto-computed-field-names.jsonnet
When finding node by position, push `field.Name` to the search stack.
This allows us to now search through the field names as well when finding
definitions.
=> Enable go-to-definition for computed field names.

pkg/server/definition.go, pkg/server/hover.go, pkg/server/server.go, pkg/server/symbols.go
It's currently sending errors when DocumentSymbol fails to parse
This happens VERY often, causing the language server to kill itself
=> Use standard error pattern for `DocumentSymbol`, do not error out when parsing fails

pkg/ast_processing/find_field.go, pkg/nodestack/nodestack.go, pkg/server/definition_test.go, pkg/server/testdata/goto-functions-advanced.libsonnet
When processing the index list, the language server will now go through function bodies to find fields
This will only occur when the function's body is directly a DesugaredObject
This doesn't support all cases. I will probably have to add more, I have already identified cases which are even more complex that do not work yet, but this is a good first step
In the `go-to-functions-advanced.libsonnet` file, this allows us to find the `arg2` field accessed later on, even though it's a field created by a function
=> Basic go-to-definition inside functions

pkg/ast_processing/object_range.go, pkg/server/symbols.go, pkg/server/symbols_test.go, pkg/server/testdata/goto-computed-field-names.jsonnet
Bug introduced in https://github.com/grafana/jsonnet-language-server/pull/60
The server currently panics while trying to get symbols when there's a computed field present
This will instead list the fields at `[field.content]` in symbols
=> Support symbols for computed fields

pkg/ast/processing/find_field.go, pkg/server/configuration_test.go, pkg/server/definition_test.go, pkg/server/testdata/goto-functions-advanced.libsonnet
Fetching attributes through builder pattern + mixins
=> Support more functions

pkg/ast/processing/find_field.go
There's a continue without a i++ there, this could possibly loop forever
I also removed some unnecessary stacks, should be much faster
=> Simplify code and prevent infinite loop

.github/workflows/benchstat-pr.yml, pkg/server/completion.go, pkg/server/completion_test.go, pkg/server/definition_test.go, pkg/server/testdata/test_basic_lib.libsonnet
Closes https://github.com/grafana/jsonnet-language-server/issues/3
=> Add basic completion for `self` fields and locals

pkg/server/server.go
=> Fix index access panic

pkg/ast/processing/find_field.go, pkg/ast/processing/top_level_objects.go, pkg/nodestack/nodestack.go, pkg/server/definition_test.go, pkg/server/testdata/goto-root-function-lib.libsonnet, pkg/server/testdata/goto-root-function.jsonnet
Started in https://github.com/grafana/jsonnet-language-server/pull/63 and https://github.com/grafana/jsonnet-language-server/pull/70 
I think this now covers all (or most) cases
Most of this PR is just tests, since the missing code was just a few missing switch cases
=> Find definitions through function applies

pkg/server/completion.go, pkg/server/completion_test.go
Closes https://github.com/grafana/jsonnet-language-server/issues/4 
Also:
+ Sort the list of suggestions by label
+ Ignore lines ending with `,` or `;`. This happens when a user is replacing an index in an existing line (refactoring, etc)
=> Completion from dollar sign: Basic case

pkg/stdlib/stdlib-content.jsonnet
This should add the `splitLimitR`, `all` and `any` functions to autocomplete + hover
=> Pull stdlib content from v0.19.0

nix/default.nix
Builds are failing because there is a mismatch in the vendoring required for `go build` and the vendoring that results from the vendorSha256 fixed output derivation. 
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
=> Update the sha256 sum for vendored go modules

pkg/ast/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-multilevel-library-main.jsonnet, pkg/server/testdata/goto-multilevel-library-sub-1.1.libsonnet, pkg/server/testdata/goto-multilevel-library-sub-1.2.libsonnet, pkg/server/testdata/goto-multilevel-library-sub-1.libsonnet, pkg/server/testdata/goto-multilevel-library-sub-2.libsonnet, pkg/server/testdata/goto-multilevel-library-top.libsonnet
This adds a new test case that (hopefully) contains all the ways to reference something by import 
Fixed by doing recursive processing in a place where we weren't
=> Yet another import case

pkg/ast/processing/find_field.go, pkg/ast/processing/find_param.go, pkg/ast/processing/object_range.go, pkg/ast/processing/top_level_objects.go, pkg/server/completion.go, pkg/server/completion_test.go, pkg/server/definition.go
Closes https://github.com/grafana/jsonnet-language-server/issues/5 
Simplified the code in the process.
Completion was using it's own stack-walking code, I moved it to use the same thing as go-to-definition, so it should support all the cases now. From multi-level indexing to overrides and imports
Demo:
https://user-images.githubusercontent.com/29210090/235547179-465b6d3c-bd29-4a9b-93cd-ef40c269fb17.mp4
=> Full completion support

pkg/ast/processing/top_level_objects.go, pkg/server/completion_test.go, pkg/server/testdata/local-at-root-2.jsonnet, pkg/server/testdata/local-at-root-3.jsonnet, pkg/server/testdata/local-at-root-4.jsonnet, pkg/server/testdata/local-at-root.jsonnet
Closes https://github.com/grafana/jsonnet-language-server/issues/113
This also fixes the go-to-definition functionality for this case, since it's the same code
=> Completion: Fix completion through an import pointing to a local bind

pkg/server/completion.go
When doing auto-complete, it currently shows `*ast.Index` when it's nested Indexing because we don't follow up to the final ref 
Instead of `ast.Index`, we can say `object field` which makes a bit more sense for users
=> Add label when completing a nested index

nix/default.nix
This PR updates the version of the flake to match latest and updates the sha of vendored dependencies to match as well.
=> update vendor sha signature and bump version in flake

pkg/ast/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-infinite-recursion-bug-1.jsonnet, pkg/server/testdata/goto-infinite-recursion-bug-2.libsonnet, pkg/server/testdata/goto-infinite-recursion-bug-3.libsonnet
When dealing with CRDsonnet libraries in our (Grafana Labs) repositories, the language server would lock up and use up all my CPU:
- I thought it had something to do with CRDsonnet but I was wrong.
- This happened because it was trying to find a field in the wrong nodestack repeatedly (see image). It didn't crash because it didn't loop quick enough?
- This PR fixes the issue.
- Obviously, the language server can't find fields that come from processing jsonschema, but at least it doesn't take up 4 full CPUs (it reached 1% CPU usage while testing :) )
=> Fix world's slowest stack overflow

pkg/ast/processing/find_field.go, pkg/server/completion_test.go, pkg/server/testdata/doubled-index-bug-1.jsonnet, pkg/server/testdata/doubled-index-bug-2.jsonnet, pkg/server/testdata/doubled-index-bug-3.jsonnet, pkg/server/testdata/doubled-index-bug-4.jsonnet
woops
Closes https://github.com/grafana/jsonnet-language-server/issues/122
=> Fix double completion bug

pkg/ast/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/grafonnet/eval-variable-options.jsonnet
Depends on https://github.com/grafana/jsonnet-language-server/pull/127
It was only looking through a single level of binaries, so the following didn't work:
`obj1 + obj2 + obj3` which in the AST is:
binary(binary(obj1, obj2), obj3)
=> Fix: Go-to definition on recursive binary operators

editor/emacs/jsonnet-language-server.el
Send settings on LSP client initialization.  Note jsonnet-language-server is unusual and expects configuration without a prefix.  This is probably a bug in jsonnet-language-server, but this PR works with the existing code by passing through the "jsonnet" settings subtree, without the "jsonnet" prefix.
Example:
```elisp
;; .emacs
(lsp-register-custom-settings
'(("jsonnet.formatting"
;; jsonnetfmt --string-style d --comment-style s
((StringStyle . "double")
(CommentStyle . "slash")))))
```
=> Send settings on client initialization

nix/default.nix, nix/flake.lock, nix/flake.nix, nix/shell.nix, nix/snitch.nix
bumps the jsonnet-language-server version to the latest (0.13.1) and removes the deprecated `vendorSha256` properties from the nix derivations/packages (replacing with `vendorHash`)
=> nix: update to 0.13.1 and remove deprecated vendorSha256

pkg/server/completion.go
Follow up on #136, this uses the upstream go-jsonnet formatter. It still feels a bit dirty but I feel much more confident that this will result in correct behavior.
=> fix(completion): use upstream go-jsonnet Formatter

pkg/ast/processing/find_position.go, pkg/server/definition_test.go, pkg/server/testdata/goto-assert-var.jsonnet
Also refactored `FindNodeByPosition`: All the function does is find the children of nodes, `go-jsonnet` has a helper for that
Closes https://github.com/grafana/jsonnet-language-server/issues/128
=> Support `assert` statements

pkg/ast/processing/find_field.go, pkg/server/completion.go, pkg/server/completion_test.go, pkg/server/testdata/goto-functions.libsonnet
Closes https://github.com/grafana/jsonnet-language-server/issues/129 
Had to implement a more sophisticated word-splitting function because `myfunc(arg1, arg2) has to be a single "word"
=> Auto-complete function body attributes

pkg/server/cache.go, pkg/server/hover.go, pkg/server/hover_test.go
Closes https://github.com/grafana/jsonnet-language-server/issues/8 
Closes https://github.com/grafana/jsonnet-language-server/issues/9 
Closes https://github.com/grafana/jsonnet-language-server/issues/10
Next step will be to support docsonnet: https://github.com/grafana/jsonnet-language-server/issues/109 to get some proper descriptions
=> Support hover on all tokens

pkg/ast/processing/find_field.go, pkg/ast/processing/processor.go, pkg/ast/processing/top_level_objects.go, pkg/server/completion.go, pkg/server/definition.go
Instead of carrying a `cache` and `vm` around on each function, create a `Processor` struct to contain those
=> Simplify processing args

.golangci.toml, pkg/ast/processing/find_field.go, pkg/ast/processing/processor.go, pkg/ast/processing/top_level_objects.go, pkg/cache/cache.go, pkg/server/completion.go, pkg/server/configuration_test.go, pkg/server/definition.go, pkg/server/diagnostics.go, pkg/server/diagnostics_test.go, pkg/server/execute.go, pkg/server/formatting.go, pkg/server/hover.go, pkg/server/server.go, pkg/server/symbols.go
Closes https://github.com/grafana/jsonnet-language-server/issues/133
There are two caches currently:
- One for protocol documents. This one is instantiated by the server and maintained up-to-date as documents are opened, changed, and closed.
- One for jsonnet objects. This one is a global var and is only added to. Modified objects are never removed/modified from the cache.
By merging the two caches, we can expand the first cache's behavior to also invalidate modified objects from the global cache when a document is changed.
=> Global cache for documents + top level jsonnet objects

pkg/cache/cache.go, pkg/server/server.go
... whenever files are changed. The reason for that is that it's hard to figure out where imports actually lead, so invalidations sometimes won't happen, leading to invalid language server suggestions
=> Invalidate the whole "top level objects" cache

pkg/ast/processing/find_field.go, pkg/server/definition_test.go, pkg/server/testdata/goto-builder-pattern.jsonnet
Found some cases where go-to-definition was not working properly
=> Support builder pattern better

pkg/ast/processing/find_field.go
This is used twice and it's complex enough that it can be extracted
=> Extract `findSelfObject`

pkg/ast/processing/find_field.go, pkg/ast/processing/object_range.go, pkg/cache/cache.go, pkg/server/hover_test.go, pkg/server/symbols.go, pkg/server/symbols_test.go, pkg/server/testdata/conditional-fields.jsonnet
Closes https://github.com/grafana/jsonnet-language-server/issues/166
Symbols are now always strings. If field names are complex nodes, then we use the actual jsonnet
=> Fix symbols crashing

.github/workflows/golangci-lint.yml, .github/workflows/jsonnetfmt.yml, .github/workflows/release.yml, .github/workflows/test.yml
Securing GH actions as followup from [the incident on April 26th 2025](https://grafana.com/blog/2025/04/27/grafana-security-update-no-customer-impact-from-github-workflow-vulnerability/).
<details><summary>before</summary>
<p>
```
$ git remote -v; zizmor --gh-token=$(gh auth token) .
origin	https://github.com/grafana/jsonnet-language-server.git (fetch)
origin	https://github.com/grafana/jsonnet-language-server.git (push)
INFO audit: zizmor: 🌈 completed ./.github/workflows/golangci-lint.yml
INFO audit: zizmor: 🌈 completed ./.github/workflows/jsonnetfmt.yml
INFO audit: zizmor: 🌈 completed ./.github/workflows/release.yml
INFO audit: zizmor: 🌈 completed ./.github/workflows/test.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
--> …
```
=> Apply StepSecurity and zizmor fixes
